export enum StringConstants {
    BANK_ACCOUNT_NOT_FOUND = "Bank account not found",
    BANK_ACCOUNT_SAVED = "Bank account saved successfully",
    CONFIRM_EMAIL = "Confirm your email",
    CREATOR_OPPONENT_ID_MISSING = "Creator or Opponent ID is missing",
    EMAIL_ALREADY_VERIFIED = "Email is already verified.",
    EMAIL_VERIFICATION_SUCCESS = "Email verified successfully",
    EMAIL_NOT_VERIFIED = "Email is not verified.",
    EMAIL_ALREADY_IN_USE = "Email is already in use",
    EMAIL_ALREADY_EXISTS = "User with this email already exists",
    EXPIRED_TOKEN= "Token Expired",
    INVALID_TOKEN= "Invalid Token",
    PASSWORD_RESET_LINK_SENT = "Password reset link has been sent to your email address.",
    FAILED_USER_FETCH = "Failed to fetch users",
    FAILED_USER_UPDATE = "Failed to update user",
    FAILED_USER_DELETE = "Failed to delete user",
    FAILED_TRANSACTION = "Transaction failed or incomplete",
    INVALID_CREDENTIALS = "Invalid user credentials",
    INVALID_PASSWORD = "Invalid password. Kindly enter new password.",
    INVALID_EXPIRED_TOKEN = "Invalid or Expired Token",
    PRIMARY_BANK_ACCOUNT_SET = "Primary bank account set successfully",
    PASSWORD_RESET_SUCCESSFUL = "Password has been reset successfully.",
    REGISTRATION_ERROR = "An error occurred during registration",
    REGISTRATION_SUCCESS = "User registered successfully",
    SIGNUP_SUCCESSFUL = "Confirmation code sent to email.",
    USER_NOT_FOUND = "User not found",
    VERIFICATION_CODE_SENT = "Verification code sent",
    WALLET_NOT_FOUND = "Wallet not found",
  }
  
  